### ISSUE TITLE
Could not load ipadapter_file

### ISSUE THREAD

**Issue by songproducer** [cubiq/ComfyUI_IPAdapter_plus#137]
comfyUI is up to date and I have ip-adapter-plus_sd15.bin in the controlnet folder.

The load IPadapter model just shows 'undefined'

**Comment by cubiq** [comment]
stop comfy, copy the model into ComfyUI/models/ipadapter and retry

**Comment by songproducer** [comment]
Thanks,  I'll try it tomorrow and let you know how I go!

**Comment by cubiq** [comment]
I gather it's solved now

**Comment by tetsuoo-online** [comment]
Same issue here.
ComfyUI is updated, the custom nodes as well
I tied to put the BIN files : 
- in models\ipadapter
- in models\ipadapter\models
- in models\IP-Adapter-FaceID
- in custom_nodes\ComfyUI_IPAdapter_plus\models

I even tried to edit custom paths (extra_model_path.yaml), nothing worked.
I already reinstalled ComfyUI yesterday, it's the second time in 2 weeks, I swear if I have to reinstall everything from scratch again I'm gonna give up

**Comment by Okachobe** [comment]
I dont have a solution for you, im running into the same issue even after putting the model where it says it should go, but if you might want to create a docker file or a github repo with how you like your repository and set it up to grab all the models for you automatically when you have to set things up again. id use chat gpt for how to do that because theres some good starter points already made.

**Comment by Okachobe** [comment]
Alright so that node is actually out of date it seems idk if the image will load but i replaced that node with load ipadapter model and apply ipaadapter model and just rewiring appropriately, was pretty easy after the fact. 

![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/45910456/0fd50b96-7f17-4180-b9be-62e7782cc20c)

**Comment by PancrasPZ** [comment]
I just edited the file folder_paths.py in ComfyUI.
Add a line of 
folder_names_and_paths["ipadapter"] = ([os.path.join(models_dir, "ipadapter")], supported_pt_extensions)

and now it works.

**Comment by Virgile-fr** [comment]
> I just edited the file folder_paths.py in ComfyUI. Add a line of folder_names_and_paths["ipadapter"] = ([os.path.join(models_dir, "ipadapter")], supported_pt_extensions)
> 
> and now it works.

it work for me, thanks :)

**Comment by ShowerElf** [comment]
> I just edited the file folder_paths.py in ComfyUI. Add a line of folder_names_and_paths["ipadapter"] = ([os.path.join(models_dir, "ipadapter")], supported_pt_extensions)
> 
> and now it works.

It worked for me, too!!! Thanks very much!!!!!!!

**Comment by HT-Sun** [comment]
It worked for me, too!!! Thanks very much!!!!!!!
