### ISSUE TITLE
Weights only load failed

### ISSUE THREAD

**Issue by UrsaBaby** [cubiq/ComfyUI_IPAdapter_plus#164]
Hi. I keep getting this error when trying to use this:
"Error occurred when executing IPAdapterModelLoader:

Weights only load failed. Re-running `torch.load` with `weights_only` set to `False` will likely succeed, but it can result in arbitrary code execution.Do it only if you get the file from a trusted source. WeightsUnpickler error: Unsupported operand 60"

Ive tried updating comfy, downloaded the nodes directly from repository and so on. Cant find any info on this error. Any tips?

**Comment by cubiq** [comment]
what system are you on? post the comfy init message

**Comment by UrsaBaby** [comment]
Solved. You had to rename the clip vision files. When you download them they are called model.safetensors rename it to original name and it will work. for example CLIP-ViT-bigG-14-laion2B-39B-b160k.safetensors.

**Comment by cmark3** [comment]
i got the same error when i am executing  IPAdapterModelLoader. i tried your method by changing the clip vision file's name back to CLIP-ViT-bigG-14-laion2B-39B-b160k.safetensors. however, this method did not work on me. the error remains. 
my comfy init message: 
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/155736775/1470b50f-df74-4218-8159-1926a0452cb6)

**Comment by lwc-alex** [comment]
Having the same issue, I have followed the installation readme

**Comment by lwc-alex** [comment]
Hi @cmark3 have you found a solution?

**Comment by lwc-alex** [comment]
Previously, I was using the legacy model path, i.e. `/workspace/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus/models`
Now I corrected it to: `/workspace/ComfyUI/models/ipadapter`, with the correct models there, it's working fine

**Comment by cmark3** [comment]
i tried to load the .safetensors model file instead of .bin file, then it works. so mine one is nothing to do with clip vision.
________________________________
发件人: iRonMan ***@***.***>
发送时间: 2024年1月21日 1:04
收件人: cubiq/ComfyUI_IPAdapter_plus ***@***.***>
抄送: cmark3 ***@***.***>; Mention ***@***.***>
主题: Re: [cubiq/ComfyUI_IPAdapter_plus] Weights only load failed (Issue #164)


Previously, I was using the legacy model path, i.e. /workspace/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus/models
Now I corrected it to: /workspace/ComfyUI/models/ipadapter, with the correct models there, it's working fine

―

**Comment by cartossin** [comment]
I think this problem happens when you get the model names mixed up. In my case, I downloaded the wrong file and named it "AnimateLCM_sd15_t2v.ckpt" so it crashed when trying to load whatever that file actually was. Redownloaded and it works now.

**Comment by HamedEmine** [comment]
I got this error because my model had the .ckpt extension instead of .safetensors
Renaming the extension fixed it.

**Comment by NoelNjem** [comment]
I also think this happens happens when you get the model names mixed up. In my case, I downloaded the wrong file and named it "CLIP-ViT-bigG-14-laion2B-39B-b160k" so it crashed when trying to load whatever that file actually was. Redownloaded and it works now.... But then I ran into an unrelated another error lol
