### ISSUE TITLE
Multi image faceid

### ISSUE THREAD

**Issue by TingTingin** [cubiq/ComfyUI_IPAdapter_plus#180]
Shouldn't it be possible to join face embeddings so that you can you faceid with multiple pictures potentially increasing accuracy

I know  you can use multiple faceid nodes i'm referring to sending multiple images to a node and averaging the embeddings via some metric and then using that with the adapter

**Comment by cubiq** [comment]
https://github.com/cubiq/ComfyUI_IPAdapter_plus/issues/178#issuecomment-1871081282

**Comment by krahnikblis** [comment]
@TingTingin yes, i wrote a node to do just this - grab insightface models from as many images as supplied to it, and average all of their arrays together. it does work a lot better than a single face (i use it with the ReActor nodes). i've been crawling through the code here to try to figure out how the face embedding is conditioning the denoising, can't figure it out... but i think i might make an alternate 'apply ip adapter' node which takes the pre-averaged face model, instead of the insightface function and single ref image...
