### ISSUE TITLE
Stuck at load insightface 30+ seconds, whatever  the provider is CUDA or CPU

### ISSUE THREAD

**Issue by whmc76** [cubiq/ComfyUI_IPAdapter_plus#198]
got prompt
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: E:\IMAGE\ComfyUI_windows_portable\ComfyUI\models\insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: E:\IMAGE\ComfyUI_windows_portable\ComfyUI\models\insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: E:\IMAGE\ComfyUI_windows_portable\ComfyUI\models\insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: E:\IMAGE\ComfyUI_windows_portable\ComfyUI\models\insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: E:\IMAGE\ComfyUI_windows_portable\ComfyUI\models\insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
Prompt executed in 30.68 seconds

![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/129386342/7842824a-c2ff-4f07-8c49-886f0a317b71)

**Comment by Acly** [comment]
I have the same issue with insightface in one of my Python environments. Measuring execution time for the code below:
```
from insightface.app import FaceAnalysis
model = FaceAnalysis(name="buffalo_l", root="models/insightface", providers=['CPUExecutionProvider',])
model.prepare(ctx_id=0, det_size=(640, 640))
```
Takes **37.5 seconds** in my system Python 3.11 install.
Takes **1.9 seconds** in a fresh venv with just insightface + onnxruntime

No idea which of the bazillion packages I have installed is responsible, but it has nothing to do with IP-adapter in any case...

**Comment by Acly** [comment]
Found the culprit in my case: old version of protobuf (3.20.3) was very slow. Upgrade to latest (4.25.1) fixed it:
```
python -m pip install protobuf --upgrade
```

**Comment by whmc76** [comment]
> Found the culprit in my case: old version of protobuf (3.20.3) was very slow. Upgrade to latest (4.25.1) fixed it:在我的情况下找到了罪魁祸首：旧版本的 protobuf （3.20.3） 非常慢。升级到最新版本（4.25.1）修复了它：
> 
> ```
> python -m pip install protobuf --upgrade
> ```

Thank you very much for sharing, but I tried it without success. I know this should have nothing to do with the ipa, but I can only ask the professionals how to solve this problem as much as possible through the limited information.

**Comment by Arcitec** [comment]
> Found the culprit in my case: old version of protobuf (3.20.3) was very slow. Upgrade to latest (4.25.1) fixed it:
> 
> ```
> python -m pip install protobuf --upgrade
> ```

@Acly You are 100% correct.

```sh
$ python test-insightface.py
real	0m33.353s

$ pip install --upgrade protobuf
Requirement already satisfied: protobuf in ./.venv/lib/python3.11/site-packages (3.20.3)
Collecting protobuf
  Using cached protobuf-4.25.2-cp37-abi3-manylinux2014_x86_64.whl.metadata (541 bytes)
Using cached protobuf-4.25.2-cp37-abi3-manylinux2014_x86_64.whl (294 kB)
Installing collected packages: protobuf
  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.20.3
    Uninstalling protobuf-3.20.3:
      Successfully uninstalled protobuf-3.20.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
mediapipe 0.10.9 requires opencv-contrib-python, which is not installed.
mediapipe 0.10.9 requires protobuf<4,>=3.11, but you have protobuf 4.25.2 which is incompatible.
Successfully installed protobuf-4.25.2

$ python test-insightface.py
real	0m1.463s
```

I ran this modified code:

```py
from insightface.app import FaceAnalysis
model = FaceAnalysis(name="buffalo_l", root="comfyui/models/insightface", providers=['CPUExecutionProvider',])
model.prepare(ctx_id=0, det_size=(640, 640))
```

I looked into my folder since I have most of the "popular, must-have node collections". For me, the dependency graph goes as follows:

- `comfyui_controlnet_aux/requirements.txt`: mediapipe
- mediapipe: https://github.com/google/mediapipe/blob/master/requirements.txt
- mediapipe requirements.txt: `protobuf>=3.11,<4`

Basically, any ComfyUI module which pulls in `mediapipe` is automatically pulling in an old version of Protobuf, because Google has specified that mediapipe requires version 3 of Protobuf. So it gets the newest 3.x version. Which is slow as hell.

I had a very quick look into `comfyui_controlnet_aux` (the only modules I have which use mediapipe), and see that it's using `mediapipe_face`, and specifically it seems to only be using the `MediapipeFaceDetector` class. So even if `mediapipe` breaks by upgrading `protobuf`, it doesn't seem to be an important part of the controlnet aux package. In fact, I bet it's only used by the "ControlNet Preprocessors: Faces and Poses Estimators: Mediapipe Face Mesh" node. But I see references to `import mediapipe` in several source files in a ripgrep search, so I can't say for sure.

All I know is that upgrading Protobuf fixes the speed. Amazing find. Thank you so much.

**Comment by marimatt** [comment]
In our case, with python 3.10.13, our problem was resolved by commenting this env in the dockerfile:


```
PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
``` 

with this env activated, it takes 90 seconds to load:

insightface.app.FaceAnalysis(name='buffalo_l', root=MODEL_ROOT_INSIGHTFACE, providers=providers)


while without the env, it taks 1 second :-O
