### ISSUE TITLE
Efficiency Nodes changes the render?

### ISSUE THREAD

**Issue by alenknight** [cubiq/ComfyUI_IPAdapter_plus#203]
not a bug... just a question.... and thanks for this amazing set of nodes, super helpful!  When i'm using efficiency nodes... i'm getting a slightly different render... and i'm trying as much as possible to keep it the same as your example workflow.
just at a quick glance... got any ideas what i might be doing that's causing these 2 renders to be different?

![compare](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/22153900/11687318-d2c1-465b-9b93-718d098a051a)

**Comment by alenknight** [comment]
ah i found the cause... it's from the CLIP in efficiency nodes (sorry asking here... i'll ask the efficiency folks).  odd... cause i can't see WHY it's doing that....

**Comment by stephantual** [comment]
@alenknight  Efficiency nodes is a source of headaches more than anything else. CR offers the same feature set without the requirement of 'script' and 'dependencies' that plague EFF. Eff also abstracts so much stuff you completely use the ability to use CLIP_G and CLIP_L because the author thinks 'it's best that way'. The issue is a certain site and youtuber that are pushing it as if it was the second coming, when in fact it just abstract things to the point where I can't even tell which way is up :) 

**I know it's a bit of a rant, but please don't take it as a slight, to the contrary.** I use EFF when I need to do a very quick xy compare of cfg vs steps on a new model and stash it in a collection somewhere. But my 'work' setup is entirely free of eff nodes - so much more control over the output (and the capability to make xy grid ANYWHERE, not just where eff tells you to) i get from trung's 0246 or just gridnode.
