### ISSUE TITLE
Why is the IPadapter in the model chain?

### ISSUE THREAD

**Issue by bosbrand** [cubiq/ComfyUI_IPAdapter_plus#60]
Why is the IPadapter in the model chain? If it is a true text prompt, why doesn't it output conditioning? 
I'm asking because I wonder if you could modify the output. A problem I come across is that there is no control over what it takes from an input picture. If I input a photo it very stronlgy tends to output a photo, no matter what I say in the prompt or whatever LoRAs I throw at it. 

I have two ideas:
- an option to modify aspects of the image prompt, for instance -photo, (photo:-1) or just a negative textbox. 
- an option to use the entire IP adapter in the negative, so essentially saying "this picture is what you should not produce". This way you can use an output as feedback. 

Let me know what you think!

**Comment by cubiq** [comment]
IPAdapter patches the model it's not only about conditioning (that's why it is so effective) so it needs to pass through the model pipeline. The visual embeds are then concat'd with the text embeds in the ksampler. You can use the "light" model if you need very light conditioning or set a very low weight. Weight can also be negative actually, but the effect is not probably what you are expecting.

Regarding the negative image prompting, it is technically feasible and I actually use that feature for the "noise" option but the result is very unpredictable because of how aggressive the models are at tokenizing an image (ie: you end up adding negative tokens of things that you don't want).

**Comment by bosbrand** [comment]
Thank you for taking the time to explain! Would it be possible to read the embeds and see what the tokenizing is like? The clip model should produce something like natural language, right? I find myself guessing all the time what it is that the clipmodel 'sees'. Is the embedding anything like a textual inversion embedding?

**Comment by cubiq** [comment]
You can try to convert an image into a text (there are many tools available) but it's just a guesstimate, we don't know how the IPAdapter models are trained, once encoded I don't think there's any way to "reverse engineer" the embeds.
