### ISSUE TITLE
IPAdapter_image_encoder_sd15.safetensors?  where are folks getting this from?

### ISSUE THREAD

**Issue by alenknight** [cubiq/ComfyUI_IPAdapter_plus#66]
I keep getting an error when loading clipvision from the sample workflows - saying IPAdapter_image_encoder_sd15.safetensors is not found.  where are folks getting this from?  
I went to https://huggingface.co/h94/IP-Adapter/tree/main - but it's not there.  I see it on lots of YT tutorials too... so I'm sure it's out there, just I'm confused where folks got it from

**Comment by cubiq** [comment]
it's linked in the documentation. Just rename it to IPAdapter_image_encoder_sd15.safetensors or to whatever you want actually.

**Comment by alenknight** [comment]
> it's linked in the documentation. Just rename it to IPAdapter_image_encoder_sd15.safetensors or to whatever you want actually.

ahhhhh those image encoder `model.safetensors` files?  thanks!

**Comment by cubiq** [comment]
you got it! :)

**Comment by jaykumarsara** [comment]
Still I Am Searched.
https://huggingface.co/h94/IP-Adapter/tree/main/models/image_encoder
i think this one. Thanks @alenknight

**Comment by stepahin** [comment]
So... Which one of the two model.safetensors? Yes I see **sd15** in the new name, but what if YT tutorial / workflow about SDXL? Sorry I'm a bit confused about this renaming :/

h94/IP-Adapter/tree/main/**models**/image_encoder/model.safetensors
OR
h94/IP-Adapter/tree/main/**sdxl_models**/image_encoder/image_encoder/model.safetensors

**Comment by alex-mitov** [comment]
> So... Which one of the two model.safetensors? Yes I see **sd15** in the new name, but what if YT tutorial / workflow about SDXL? Sorry I'm a bit confused about this renaming :/
> 
> h94/IP-Adapter/tree/main/**models**/image_encoder/model.safetensors OR h94/IP-Adapter/tree/main/**sdxl_models**/image_encoder/image_encoder/model.safetensors

I assume the first link is the SD 1.5 one given that the second link has "SDXL" in its name.

**Comment by dryodryo** [comment]
Why can't developers give their models unique names? Just "model.safetensors"??? This is insane. How can people who are obviously so smart be so incredibly clueless?

Incredible effort and massive detective work required to do anything at all

**Comment by That-Ruben** [comment]
> Why can't developers give their models unique names? Just "model.safetensors"??? This is insane. How can people who are obviously so smart be so incredibly clueless?
> 
> Incredible effort and massive detective work required to do anything at all

It's a subtle form of gatekeeping

**Comment by cubiq** [comment]
it's the huggingface format where the actual model name is `repository-owner/repository-name/model-type/model.safetensors`

so the model is actually uniquely identified, it's other software like comfy or a1111 that decided they didn't like it and wanted to work directly on the one file name.

**Comment by memo** [comment]
Also, an entire directory is better suited to represent a model, because many models require additional files like config jsons, important readmes etc. So it makes more sense to have a unique identifier as the folder name, and then standardized filenames inside. And that's how they're typically stored on huggingface.

**Comment by dryodryo** [comment]
It's not a subtle form of gatekeeping, it's totally overt.

Just because some system has been set up to assume standardized filenames does not mean that this is the best way. It may be convenient for developers, but it's living hell for users.

The biggest problem with AI generation is the fact that it's an emerging field with two kinds of people using it. Expert level developers and clueless newbs. And the experts have no motivation to make their work accessible. Even if they wanted to, they usually don't have the skills. It takes people in the middle to translate: UX designers, technical writers, etc.

From the point of view of a developer trying to save time, using the same filenames in every project makes sense.

From the point of view of a user trying to accomplish the actual purpose of the software, using the same filenames is a massive inconvenience. We need to rename the models? What should be rename them to? How do we share our work with others when every one of us has to rename the model files? This standardization in the development process leads to total chaos in the actual USAGE of the product!

The disconnect between development and usage is incredibly massive here. Won't someone think of the children???

**Comment by icemagno** [comment]
> It's not a subtle form of gatekeeping, it's totally overt.
> 
> Just because some system has been set up to assume standardized filenames does not mean that this is the best way. It may be convenient for developers, but it's living hell for users.
> 
> The biggest problem with AI generation is the fact that it's an emerging field with two kinds of people using it. Expert level developers and clueless newbs. And the experts have no motivation to make their work accessible. Even if they wanted to, they usually don't have the skills. It takes people in the middle to translate: UX designers, technical writers, etc.
> 
> From the point of view of a developer trying to save time, using the same filenames in every project makes sense.
> 
> From the point of view of a user trying to accomplish the actual purpose of the software, using the same filenames is a massive inconvenience. We need to rename the models? What should we rename them to? How do we share our work with others when every one of us has to rename the model files? This standardization in the development process leads to total chaos in the actual USAGE of the product!
> 
> The disconnect between development and usage is incredibly massive here. Won't someone think of the children???

Damn man!! You got right to the point about things that have been on my mind for a time. I'm extremely annoyed with this IPAdapter because it's only talked about for certain tasks (no options) and developers are breaking all the legacy code all the time. I've tried 9 workflows with different approaches and none of them worked. Now I find out that I have to worry about filenames because of this damned and obscure "Unified Model Loader". These people don't understand that when they break code they also break people's work. And so they look for other more stable options.

**Comment by cubiq** [comment]
the old loaders are still available
