### ISSUE TITLE
InisightFace Error, on "correct" install?

### ISSUE THREAD

**Issue by NullEqualsZero** [cubiq/ComfyUI_IPAdapter_plus#724]
### Your question

What is the proper way to install `insightface` I think I have installed it correctly
![Screenshot 2024-09-27 202847](https://github.com/user-attachments/assets/27f0ebbf-2a92-44cd-aa67-61da580d0c40)
![image](https://github.com/user-attachments/assets/7358077f-1cb2-4e7a-be9a-b09908d42ecd)

I think I have downloaded right, but it is still not working!

### Logs

```powershell
>python_embeded\python.exe -m pip show insightface
Name: insightface
Version: 0.7.3
Summary: InsightFace Python Library
Home-page: https://github.com/deepinsight/insightface
Author: InsightFace Contributors
Author-email: contact@insightface.ai
License: MIT
Location: E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages
Requires: albumentations, cython, easydict, matplotlib, numpy, onnx, Pillow, prettytable, requests, scikit-image, scikit-learn, scipy, tqdm
Required-by:

E:\ComfyUI_windows_portable>python_embeded\python.exe -m pip install onnxruntime
Requirement already satisfied: onnxruntime in e:\comfyui_windows_portable\python_embeded\lib\site-packages (1.19.2)
Requirement already satisfied: coloredlogs in e:\comfyui_windows_portable\python_embeded\lib\site-packages (from onnxruntime) (15.0.1)
Requirement already satisfied: flatbuffers in e:\comfyui_windows_portable\python_embeded\lib\site-packages (from onnxruntime) (24.3.25)
Requirement already satisfied: numpy>=1.21.6 in e:\comfyui_windows_portable\python_embeded\lib\site-packages (from onnxruntime) (1.26.4)
Requirement already satisfied: packaging in e:\comfyui_windows_portable\python_embeded\lib\site-packages (from onnxruntime) (23.2)
Requirement already satisfied: protobuf in e:\comfyui_windows_portable\python_embeded\lib\site-packages (from onnxruntime) (4.25.5)
Requirement already satisfied: sympy in e:\comfyui_windows_portable\python_embeded\lib\site-packages (from onnxruntime) (1.13.2)
Requirement already satisfied: humanfriendly>=9.1 in e:\comfyui_windows_portable\python_embeded\lib\site-packages (from coloredlogs->onnxruntime) (10.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in e:\comfyui_windows_portable\python_embeded\lib\site-packages (from sympy->onnxruntime) (1.3.0)
Requirement already satisfied: pyreadline3 in e:\comfyui_windows_portable\python_embeded\lib\site-packages (from humanfriendly>=9.1->coloredlogs->onnxruntime) (3.5.4)

E:\ComfyUI_windows_portable>
```

### Other

System: Windows 11
On the latest Update both ComfyUI and all the extension
Using the portable installation of ComfyUI

**Comment by Reftek85** [comment]
same issue here

**Comment by Reftek85** [comment]
Hi,
I stumbled on this post https://github.com/Gourieff/comfyui-reactor-node/discussions/460  after days of the same error, my install is brand new from last week.. I reinstalled everything from scratch  because I couldn't figure it out and again same error....

I found that I was getting this line the first time an ipadapter model was loaded with a different checkpoint,
`!!! Exception during processing !!! numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject`

In this other post  I found the command to update numpy to the version of python that I have with my fresh install (python 3.12), it works after the update and a restart of ComfUI.


if your python version is 3.12 use this command in the root folder:
`.\python_embeded\python.exe -m pip install numpy===1.26.4`


if your python version is 3.11 use this command in the root folder: 
`.\python_embeded\python.exe -m pip install numpy===1.25.2`



I really wish the error box that show on screen would give us the real missing files or missing dependencies instead of sending us in the wrong directions.

I hope it helps you and others.
